version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gogochat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "gogochat"     # 对应 mysqlConfig.databaseName（自动创建该库）
      MYSQL_ROOT_HOST: "%"           # 允许所有地址访问（测试环境简化，生产需限制）
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    # 禁用数据持久化（测试用，容器删了数据就没）

  redis:
    image: redis:7.0
    container_name: gogochat-redis
    restart: always
    command: redis-server --requirepass "123456"
    ports:
      - "6379:6379" 
    # 禁用数据持久化
